version: "3.5"

services:
    web:
        image: demo-nginx:3.0
        ports:
            - "8080:80"
        depends_on:
            - php-demo
            - mysql
        networks:
            - default
        environment:
            - UPSTREAM=php-demo:9000
    php-demo:
        image: demo-php:9.5
        networks:
            - default
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7.33
        networks:
            - default
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: demo
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql


